name 'boilerplate_php'
maintainer 'topaz2'
maintainer_email 'topaz2@m0n0m0n0.com'
license 'GPL v3'
description 'Installs/Configures boilerplate_php'
version '0.3.0'

depends 'apache2'
depends 'jenkins'
depends 'php'
depends 'python'
depends 'composer'
depends 'boilerplate'
depends 'application'
# depends 'application_php'
