#!/bin/bash -e

DIRNAME="$(dirname -- "$0")"
HOOKS="<%= node[:boilerplate_php][:git][:hooks].values.sort.join(' ') %>"

export PATH=$PATH:/var/www/app/vendors/bin

for HOOK in $HOOKS
do
  echo "Running hook: $HOOK"
  if [ -x "$DIRNAME/$HOOK" ]
  then
    "$DIRNAME/$HOOK" || exit $?
  else
    echo "Error: file $HOOK not found."
    exit 1
  fi
done

exit 0
