#!/bin/bash -ex

DIRNAME="$(dirname -- "$0")"
HOOKS="<%= node[:boilerplate_php][:git][:hooks] %>"

for HOOK in $HOOKS
do
  echo "Running hook: $HOOK"
  if [ -f "$DIRNAME/$HOOK" ]; then
    "$DIRNAME/$HOOK" || exit $?
  else
    echo "Error: file $HOOK not found."
    exit 1
  fi
done

exit 0
