#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`

FILES=""
for FILE in `git diff --cached --name-only --diff-filter=ACMR HEAD | egrep \\\\.\(php\|ctp\)\$`
do
  FILES="$FILES $PROJECT/$FILE"
done
FILES_CSV=`echo $FILES | sed 's/\s/,/g'`

if [ "$FILES_CSV" != "" ]
then
  echo "Running phpmd..."
  phpmd $FILES_CSV text ruleset/phpmd.xml || exit $?
fi

exit 0
