#!/bin/bash -e

PROJECT=`pwd`
APP=""
if [ ! -z `echo $PROJECT | egrep 'app/Plugin'` ]
then
  APP=`echo $PROJECT | sed 's/\w\+\/\w\+\/\w\+$//'`
fi

FILES=""
for FILE in `git diff --cached --name-only --diff-filter=ACMR HEAD | egrep \\\\.\(php\|ctp\)\$`
do
  FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
  echo "Running phpunit..."
  for TEST in `git diff --cached --name-only --diff-filter=ACMR HEAD | egrep \\Test\\.\(php\)\$ | sed 's/app\/Test\/Case\/\([a-zA-Z0-9\/]\+\)Test\.php/\1/g'`
  do
    $APP/lib/Cake/Console/cake test app $TEST --stderr --configuration phpunit.xml.dist || exit $?
  done
fi

exit 0
